# Generated by Django 6.0.6 on 2026-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('FileID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='files/')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
